-- El catálogo global de ejercicios (user_id = null) ya no se siembra aquí.
-- Vive en la migración supabase/migrations/20260810183347_expand_exercise_catalog.sql,
-- que es idempotente (upsert por `slug`) y sí corre en CI vía `supabase db push`.
-- Este archivo no se ejecuta automáticamente (ver CLAUDE.md); se deja vacío
-- a propósito para no reintroducir filas duplicadas del catálogo global.
